CREATE DATABASE NORTHWIND_TRADERS;
USE NORTHWIND_TRADERS;

SELECT * FROM CATEGORIES;
SELECT * FROM CUSTOMERS;
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM SHIPPERS;


DESC ORDERS;
#CHANGING THE DATA TYPE OF 'ORDERDATE' FIELD FROM TEXT TO DATE DATA TYPE
ALTER TABLE ORDERS
MODIFY ORDERDATE DATE;

#CHANGING THE DATA TYPE OF 'REQUIREDDATE' FIELD FROM TEXT TO DATE DATA TYPE
ALTER TABLE ORDERS
MODIFY REQUIREDDATE DATE;

#CHANGING THE DATA TYPE OF 'SHIPPEDDATE' FIELD FROM TEXT TO DATE DATA TYPE
ALTER TABLE ORDERS
MODIFY SHIPPEDDATE DATE;


# KPI INDICATORS

# 1 TOTAL ORDERS
SELECT * FROM ORDERS;

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;


# 2 TOTAL REVENUE
SELECT * FROM ORDER_DETAILS;

SELECT SUM(UNITPRICE * QUANTITY) AS TOTAL_REVENUE
FROM ORDER_DETAILS;

SELECT * FROM PRODUCTS;

SELECT SUM(DISCOUNT) AS DISCOUNT_TOTAL FROM ORDER_DETAILS;

# 3 AVERAGE FREIGHT CHARGES
SELECT * FROM ORDERS;

SELECT AVG(FREIGHT) AS AVERAGE_FREIGHT_CHARGES
FROM ORDERS;


# 4 TOTAL CUSTOMERS
SELECT * FROM CUSTOMERS;

SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;



# REVENUE

# 1 REVENUE PERFORMANCE BY MONTH
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;

SELECT MONTH_, TOTAL_REVENUE
FROM
(SELECT
 MONTH(ORDERDATE) AS MONTH_NO,
 MONTHNAME(ORDERDATE) AS MONTH_,
 ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
 FROM ORDERS AS O
 JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
 GROUP BY MONTH_NO, MONTH_
 ORDER BY MONTH_NO
 ) AS a ;
 
 
# 2 TOP 5 CATEGORIES BY REVENUE 
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;

SELECT CATEGORY_NAME, ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM CATEGORIES AS C
LEFT JOIN PRODUCTS AS P ON C.CATEGORY_ID = P.CATEGORY_ID
LEFT JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


# 3 TOP 5 COUNTRIES BY REVENUE
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;

SELECT COUNTRY, ROUND(SUM(UNITPRICE*QUANTITY)) AS TOTAL_REVENUE
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY COUNTRY 
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


# 4 TOP 5 PRODUCTS BY REVENUE 
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;

SELECT PRODUCT_NAME, 
ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM PRODUCTS AS P
JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


# 5 REVENUE DISTRIBUTION BY SHIPPING COMPANIES

SELECT * FROM SHIPPERS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;

SELECT COMPANY_NAME,
ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM SHIPPERS AS S
JOIN ORDERS AS O ON S.SHIPPER_ID = O.SHIPPER_ID
JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY COMPANY_NAME;



# 6 OUR KEY CUSTOMERS (BY REVENUE)
SELECT COMPANY_NAME,
ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY COMPANY_NAME
ORDER BY TOTAL_REVENUE DESC;


# ORDERS
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;

# 1 TOTAL ORDERS BY MONTH
SELECT MONTHNAME(ORDERDATE) AS MONTH_,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY MONTH_
ORDER BY TOTAL_ORDERS DESC;


# 2 OUR TOP 5 PRODUCTS IN DEMAND
SELECT * FROM PRODUCTS;

SELECT PRODUCT_NAME,
COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM PRODUCTS AS P
JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS AS O ON OD.ORDER_ID = O.ORDER_ID
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;


# 3 TOP 5 COUNTRIES WITH THE MOST ORDERS
SELECT * FROM CUSTOMERS;

SELECT COUNTRY,
COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY COUNTRY
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;


# 4 ORDERS DISTRIBUTION BY SHIPPING COMPANIES
SELECT COMPANY_NAME,
COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM SHIPPERS AS S
JOIN ORDERS AS O ON S.SHIPPER_ID = O.SHIPPER_ID
GROUP BY COMPANY_NAME;


# FREIGHT

# 1 AVERAGE FREIGHT ACROSS SHIPPING COMAPNIES
SELECT * FROM SHIPPERS;

SELECT COMPANY_NAME,
ROUND(AVG(FREIGHT)) AS AVG_SHIPPING_COST
FROM SHIPPERS AS S
JOIN ORDERS AS O ON S.SHIPPER_ID = O.SHIPPER_ID
GROUP BY COMPANY_NAME;


# 2 TOTAL FREIGHT DISTRIBUTION ACROSS SHIPPING COMAPNIES
SELECT * FROM SHIPPERS;

SELECT COMPANY_NAME,
ROUND(SUM(FREIGHT)) AS TOTAL_SHIPPING_COST
FROM SHIPPERS AS S
JOIN ORDERS AS O ON S.SHIPPER_ID = O.SHIPPER_ID
GROUP BY COMPANY_NAME;


# 3 TOTAL FREIGHT CHARGES AS PER CATEGORIES
SELECT * FROM CATEGORIES;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM PRODUCTS;

SELECT CATEGORY_NAME,
ROUND(SUM(FREIGHT)) AS TOTAL_FREIGHT
FROM CATEGORIES AS C
JOIN PRODUCTS AS P ON C.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS AS O ON OD.ORDER_ID = O.ORDER_ID
GROUP BY CATEGORY_NAME;


# 4 AVG FREIGHT CHARGES AS PER CATEGORY
SELECT CATEGORY_NAME,
ROUND(AVG(FREIGHT)) AS AVG_FREIGHT
FROM CATEGORIES AS C
JOIN PRODUCTS AS P ON C.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
JOIN ORDERS AS O ON OD.ORDER_ID = O.ORDER_ID
GROUP BY CATEGORY_NAME;


# 5 AVG FREIGHT CHARGES COUNTRY WISE (TOP 5)
SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

SELECT COUNTRY,
ROUND(AVG(FREIGHT)) AS AVG_FREIGHT_CHARGES
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY COUNTRY
ORDER BY AVG_FREIGHT_CHARGES DESC
LIMIT 5;


# INSIGHTS

# 1 NON-PERFORMING CATEGORIES BY REVENUE 
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;

SELECT CATEGORY_NAME, ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM CATEGORIES AS C
LEFT JOIN PRODUCTS AS P ON C.CATEGORY_ID = P.CATEGORY_ID
LEFT JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY CATEGORY_NAME
ORDER BY TOTAL_REVENUE
LIMIT 5;

# 2 NON-PERFORMING PRODUCTS BY REVENUE 
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;

SELECT PRODUCT_NAME, 
ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM PRODUCTS AS P
JOIN ORDER_DETAILS AS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_REVENUE
LIMIT 5;


# 3 EMPLOYEES PERFORMANCE
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;

SELECT EMPLOYEE_NAME, ROUND(SUM(UNITPRICE * QUANTITY)) AS TOTAL_REVENUE
FROM EMPLOYEES AS E
JOIN ORDERS AS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY EMPLOYEE_NAME
ORDER BY TOTAL_REVENUE DESC;